# Site settings

paginate:            50

# Build settings
markdown:            kramdown
highlighter:         rouge
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
theme: jekyll-theme-minimal


title: Daniel Katz
email: dkatz@ucsb.edu
description: > # this means to ignore newlines until "baseurl:"
  Graduate Student in Education, Quantitative Methods, and Measurement
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: dank_atz
github_username:  danielbkatz
permalink: /:year/:month/:title.html


