# Site settings


# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed]
exclude: ['*.Rmd']
title: "Daniel Katz"
author: "Daniel Katz"
email: "dkatz@ucsb.edu"

description: > # this means to ignore newlines until "baseurl:"
  "Graduate Student in Education, Quantitative Methods, and Measurement"
url: "http://dbkatz.com"
twitter_username: dank_atz
github_username:  danielbkatz
permalink: none


